%{ if length(namespaces) == 0 ~}
---
%{ endif ~}
%{ for namespace in namespaces ~}
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}
  labels:
    ${metadata_identifier}: infrastructure_namespaces
%{ endfor ~}