%{ for secret in secrets ~}
%{ if index(secrets, secret) > 0 ~}
---
%{ endif ~}
apiVersion: v1
kind: Secret
metadata:
  name: ${secret.name}
type: Opaque
%{ for key,val in secret.attributes ~}
data:
  ${key}: ${base64encode(val)}
%{ endfor ~}
%{ endfor ~}