%{ if length(secrets) == 0 ~}
---
%{ endif ~}
%{ for secret in secrets ~}
---
apiVersion: v1
kind: Secret
metadata:
  name: ${secret.name}
  namespace: ${lookup(secret, "namespace", default_namespace)}
  labels:
    ${metadata_identifier}: infrastructure_secrets
type: ${lookup(secret, "type", "Opaque")}
data:
%{ for key,val in secret.attributes ~}
  ${key}: ${base64encode(val)}
%{ endfor ~}
%{ endfor ~}