%{ if length(services) == 0 ~}
---
%{ endif ~}
%{ for service in services ~}
---
apiVersion: v1
kind: Service
metadata:
  name: ${service.name}
  namespace: ${lookup(service, "namespace", default_namespace)}
  labels:
    ${metadata_identifier}: infrastructure_services
spec:
  type: ClusterIP
%{ if service.headless ~}
  clusterIP: None
%{ endif ~}
  ports:
    - port: ${service.port}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: ${service.name}
  namespace: ${lookup(service, "namespace", default_namespace)}
  labels:
    ${metadata_identifier}: infrastructure_services
subsets:
  - addresses:
%{ for ip in split(",", service.ips) ~}
      - ip: ${ip}
%{ endfor ~}
    ports:
      - port: ${service.port}
%{ endfor ~}