%{ for service in services ~}
%{ if index(services, service) > 0 ~}
---
%{ endif ~}
apiVersion: v1
kind: Service
metadata:
  name: ${service.name}
  labels:
    ${metadata_identifier}: infrastructure_services
spec:
  type: ClusterIP
%{ if service.headless ~}
  clusterIP: None
%{ endif ~}
  ports:
    - port: ${service.port}
%{ for ip in service.ips ~}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: ${service.name}
  labels:
    ${metadata_identifier}: infrastructure_services
subsets:
  - addresses:
      - ip: ${ip}
    ports:
      - port: ${service.port}
%{ endfor ~}
%{ endfor ~}