%{ for service in services ~}
%{ if index(services, service) > 0 ~}
---
%{ endif ~}
apiVersion: v1
kind: Service
metadata:
  name: ${service.name}
  labels:
    ${metadata_identifier}: infrastructure_services
spec:
  type: ClusterIP
%{ if service.headless ~}
  clusterIP: None
%{ endif ~}
  ports:
    - port: ${service.port}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: ${service.name}
  labels:
    ${metadata_identifier}: infrastructure_services
subsets:
  - addresses:
%{ for ip in split(",", service.ips) ~}
      - ip: ${ip}
%{ endfor ~}
    ports:
      - port: ${service.port}
%{ endfor ~}